### ISSUE TITLE
Allow text alignment to be configurable

### ISSUE THREAD

**Issue by WittyJavelin** [Reselim/beat-saber-overlay#1]
I'll get around to making a pull request for this in a bit!

**Comment by Reselim** [comment]
You're asking for an optional right-to-left layout, correct? Might be a bit tricky but I could probably get it done.

**Comment by Reselim** [comment]
You're asking for an optional right-to-left layout, correct? I considered adding that but it seemed like too much of a hassle if it wasn't going to get used often. I'll work on that now, though.

**Comment by Reselim** [comment]
Added.
