### ISSUE TITLE
Unable to use github pages overlay with 2 PC streaming setup.

### ISSUE THREAD

**Issue by megalon** [Reselim/beat-saber-overlay#10]
If you try to connect to a remote IP/Port using the overlay's github hosted page, such as
http://reselim.github.io/overlay/?ip=192.168.1.1
It will simply not show anything.

This seems to be caused by a security error.
This error is shown in Chrome:
`Mixed Content: The page at 'https://reselim.github.io/overlay/?ip=198.168.1.1' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://198.168.1.1:6557/socket'. This request has been blocked; this endpoint must be available over WSS.`

And this error in Firefox:
`SecurityError: The operation is insecure.`

The OBS Browser source runs on chrome, so I'm assuming it is getting the same error response as the one for Chrome above.

From what I can tell, this is caused by the github page enforcing HTTPS, and HTTPS doesn't allow unsecure connections to websockets.
Can you change the page to not enforce HTTPS? Would that fix this?

I was able to work around this issue by hosting the overlay locally, and then connecting to that through HTTP.

-----------
***If anyone is interested in running the overlay locally, here is a step by step guide to serve it locally and connect from your streaming PC to your gaming PC.***

**Gaming PC**
1. Download and install node if you don't have it <https://nodejs.org/en/>
2. Download and unzip the Reselim overlay somewhere on your PC <https://github.com/Reselim/beat-saber-overlay/archive/master.zip>
3. In the Reselim overlay folder, open a new powershell window. Easiest way to do this is by typing `powershell` into the file explorer address bar and pressing Enter
4. In that powershell window, type `npm i -g serve` to install the local server software. This just tells the Node Package Manager (npm) to download and install it globally
5. After that's done, type `serve` in that same powershell window, and you should be serving the Reselim overlay locally. It'll give you the URL to connect to it.
6. To test that it's working, open chrome and type `http://localhost:5000/?modifiers=test` and it should show you the black test window.
7. Get the local IP address of this PC. It's probably `192.168.1.x`. 

**Streaming PC**
After setting up the gaming pc, lets check if the connection works on your streaming PC by opening Chrome and going to the site
`http://192.168.1.x:5000/?modifiers=test&ip=192.168.1.x`  
Where 192.168.1.x is the IP of your gaming PC. Yeah it's the same IP twice, that's just how it works (tm)
Note that it *has* to be `http` for this to work. That's the issue with the github page

**Comment by Reselim** [comment]
As far as I'm aware, GitHub pages enforces HTTPS no matter what. This issue was discussed in #2, however I don't see a straightforward solution without self-hosting.

**Comment by Reselim** [comment]
Done; will replace all mentions of `reselim.github.io` with `overlay.reselim.io`.
