### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [Reselim/beat-saber-overlay#13]
Hi, just seen that the site went down ... any infos ?

**Comment by ArmyHD** [comment]
Same issue here, but fixed it by downloading the master file and add the index.html file to obs.

**Comment by Rexios80** [comment]
I might host it myself on Firebase if anyone is interested. It's free and easy to set up.

**Comment by Rexios80** [comment]
It looks like it's still hosted at https://reselim.github.io/overlay

**Comment by TomAvecLeVdsl** [comment]
Oh it came back up :) Issue resolved

**Comment by TomAvecLeVdsl** [comment]
Yes but the main site (http://overlay.reselim.io/) is down

**Comment by Reselim** [comment]
Apologies, my domain expired. The README.md has been changed with the old link.

**Comment by tompointexe** [comment]
Ok thanks :)
