### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by ByteScyz** [Reselim/beat-saber-overlay#16]
Was working earlier during the day for me and now it's throwing a 404 error saying the overlay page can't be found.

**Comment by tompointexe** [comment]
Same issue here, probably due tu cloudflare crash

**Comment by refgergg** [comment]
Same issue, hope it gets fixed soon. Was really hoping to stream today.

**Comment by tompointexe** [comment]
You can download the code and tell obs that's the browerSource is a local file :) Works realy well :)

**Comment by Gordin** [comment]
For anyone who doesn't know how to use this locally:
1. Download the repo as zip [beat-saber-overlay-master.zip](https://github.com/Reselim/beat-saber-overlay/archive/master.zip)
2. extract it somewhere
3. put `file://C:/Users/Gordin/Downloads/beat-saber-overlay-master/index.html?modifiers=scale#top`
as the URL for Browser Source in OBS. (Replace `C:/Users/Gordin/Downloads/` with the directory you extracted the repo in. Also, notice the path as URL uses `/` between directories, not `\`)

**Comment by refgergg** [comment]
> For anyone who doesn't know how to use this locally:
> 
> 1. Download the repo as zip [beat-saber-overlay-master.zip](https://github.com/Reselim/beat-saber-overlay/archive/master.zip)
> 2. extract it somewhere
> 3. put `file://C:/Users/Gordin/Downloads/beat-saber-overlay-master/index.html?modifiers=scale#top`
>    as the URL for Browser Source in OBS. (Replace `C:/Users/Gordin/Downloads/` with the directory you extracted the repo in. Also, notice the path as URL uses `/` between directories, not `\`)

This worked thx!!

**Comment by ByteScyz** [comment]
> For anyone who doesn't know how to use this locally:
> 
> 1. Download the repo as zip [beat-saber-overlay-master.zip](https://github.com/Reselim/beat-saber-overlay/archive/master.zip)
> 2. extract it somewhere
> 3. put `file://C:/Users/Gordin/Downloads/beat-saber-overlay-master/index.html?modifiers=scale#top`
>    as the URL for Browser Source in OBS. (Replace `C:/Users/Gordin/Downloads/` with the directory you extracted the repo in. Also, notice the path as URL uses `/` between directories, not `\`)

Perfect! Thank you guys.
