### ISSUE TITLE
Remote Computer Setup

### ISSUE THREAD

**Issue by jaredkotoff** [Reselim/beat-saber-overlay#2]
We use a dual computer stream setup. Beat Saber on one computer, OBS on the other computer.
I was going to make a PR with an ability to define the IP of the remote computer but there are limitations on connecting to the unsecured web socket in the HTTP plugin.

A solution to this is to forward the port on the streaming computer to the gaming computer. You run this command on your Windows streaming computer:
`netsh interface portproxy add v4tov4 listenport=6557 listenaddress=localhost connectport=6557 connectaddress=<your gaming computer's ip>`

**Comment by Reselim** [comment]
I think I might just implement this feature anyway. Probably going to switch over to the URL query for options, too.

**Comment by Reselim** [comment]
Interesting solution! I'll still probably implement the ability to use a custom IP (and/or port) anyway.

**Comment by jaredkotoff** [comment]
@ReselimI can't think of an easy way around it since chrome refuses to connect to an unsecured WebSocket over HTTPs. But, there's there another plugin like this that's hosted on an unsecured domain that allows for custom IP.

**Comment by Reselim** [comment]
Hmm, I don't think github.io will allow me to disable SSL/TLS directly. I'd have to get a domain, but I'm not sure how I feel about doing that right now.

**Comment by jaredkotoff** [comment]
Exactly. This workaround works pretty well though. It's only a one-time setup. 
I can also create an unsecured subdomain on our site if you'd like.

**Comment by jaredkotoff** [comment]
i have `http://overlay.updownleftdie.com` pointing here. just set that in the settings for this repo. If you'd like it to be anything else just let me know

**Comment by Rexios80** [comment]
@Reselim Since your domain is expired, you might want to make this solution more obvious in your readme.

**Comment by Reselim** [comment]
@Rexios80 I've already changed the link from `overlay.reselim.io` to `reselim.github.io/overlay` in the readme.

**Comment by Rexios80** [comment]
I meant the part about having the overlay on a second PC and that not working with the GitHub page because of HTTPS. And this solution fixes that.

**Comment by Rexios80** [comment]
This is what I mean
