### ISSUE TITLE
IP domain

### ISSUE THREAD

**Issue by jaredkotoff** [Reselim/beat-saber-overlay#7]
I had `overlay.updownleftdie.com` pointed to my fork while you implemented the IP setting.  
It's returning a 404 when i point it here, did you set it in the repo settings?

You also might want to include an example in the readme about how to use it. multiple query parameters might be confusing to those who don't know how to use them.

**Comment by Reselim** [comment]
When I made this public, I didn't know you could directly put a repo on github.io. I have a private repository (`reselim.github.io`) with a submodule pointing to this. Unfortunately I can't remove this as everyone is currently using `/overlay`.

I've enabled `/beat-saber-overlay` though, if you still wish to use it.
